# use a fixed random seed to guarantee that when you run the code twice you will get the same outcome
manual_seed: 0
mean: 466.0
std: 379.0
is_pad_d: True
# model configuration
model:
  # model class
  name: DeepLabv3_plus_gcn_3d
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 20
  # hidden layers of GCN
  hidden_layers: 128
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: cge
  # feature maps scale factor
  f_maps: 16
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: False
# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_dir: deepLabv3_plus_gcn_3d_256_newSplit
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: null # deepLabv3_plus_3d/best_checkpoint.pytorch # null
  pre_trained: deepLabv3_plus_gcn_3d_256_newSplit/best_checkpoint.pytorch # deepLabv3_plus_3d/best_checkpoint.pytorch
  # how many iterations between validations
  validate_after_iters: 100
  # how many iterations between tensorboard logging
  log_after_iters: 100
  # max number of epochs
  epochs: 100
  # max number of iterations
  iters: 1000000
  # model with higher eval score is considered better
  eval_score_higher_is_better: True
# optimizer configuration
optimizer:
  name: Adam # Adam, SGD
  momentum: 0.9
  nesterov: False
  # initial learning rate
  learning_rate: 0.001 # 0.001 for adam
  # weight decay
  weight_decay: 0.0001 # 0.0001 for adam
# loss function configuration
loss:
  # loss function to be used during training
  name: CrossEntropyLoss  # CrossEntropyLoss or DiceLoss
  # A manual rescaling weight given to each class.
  loss_weight: null
  # a target value that is ignored and does not contribute to the input gradient
  ignore_index: null
# evaluation metric configuration
eval_metric:
  name: MeanIoU
  # a target label that is ignored during metric evaluation
  ignore_index: null
  skip_channels:
    - 0
lr_scheduler:
  name: MultiStepLR
  milestones: [30, 60]
  gamma: 0.2
# data loaders configuration
loaders:
  train_batch_size: 2
  val_batch_size: 1
  # paths to the training datasets
  train_raw_paths:
    - '/public/pangshumao/data/spine/Case1.nii.gz'
    - '/public/pangshumao/data/spine/Case2.nii.gz'
    - '/public/pangshumao/data/spine/Case3.nii.gz'
    - '/public/pangshumao/data/spine/Case4.nii.gz'
    - '/public/pangshumao/data/spine/Case5.nii.gz'
    - '/public/pangshumao/data/spine/Case6.nii.gz'
    - '/public/pangshumao/data/spine/Case7.nii.gz'
    - '/public/pangshumao/data/spine/Case8.nii.gz'
    - '/public/pangshumao/data/spine/Case9.nii.gz'
    - '/public/pangshumao/data/spine/Case10.nii.gz'
    - '/public/pangshumao/data/spine/Case11.nii.gz'
    - '/public/pangshumao/data/spine/Case12.nii.gz'
    - '/public/pangshumao/data/spine/Case13.nii.gz'
    - '/public/pangshumao/data/spine/Case14.nii.gz'
    - '/public/pangshumao/data/spine/Case15.nii.gz'
    - '/public/pangshumao/data/spine/Case16.nii.gz'
    - '/public/pangshumao/data/spine/Case17.nii.gz'
    - '/public/pangshumao/data/spine/Case18.nii.gz'
    - '/public/pangshumao/data/spine/Case19.nii.gz'
    - '/public/pangshumao/data/spine/Case20.nii.gz'
  train_label_paths:
    - '/public/pangshumao/data/spine/mask_case1.nii.gz'
    - '/public/pangshumao/data/spine/mask_case2.nii.gz'
    - '/public/pangshumao/data/spine/mask_case3.nii.gz'
    - '/public/pangshumao/data/spine/mask_case4.nii.gz'
    - '/public/pangshumao/data/spine/mask_case5.nii.gz'
    - '/public/pangshumao/data/spine/mask_case6.nii.gz'
    - '/public/pangshumao/data/spine/mask_case7.nii.gz'
    - '/public/pangshumao/data/spine/mask_case8.nii.gz'
    - '/public/pangshumao/data/spine/mask_case9.nii.gz'
    - '/public/pangshumao/data/spine/mask_case10.nii.gz'
    - '/public/pangshumao/data/spine/mask_case11.nii.gz'
    - '/public/pangshumao/data/spine/mask_case12.nii.gz'
    - '/public/pangshumao/data/spine/mask_case13.nii.gz'
    - '/public/pangshumao/data/spine/mask_case14.nii.gz'
    - '/public/pangshumao/data/spine/mask_case15.nii.gz'
    - '/public/pangshumao/data/spine/mask_case16.nii.gz'
    - '/public/pangshumao/data/spine/mask_case17.nii.gz'
    - '/public/pangshumao/data/spine/mask_case18.nii.gz'
    - '/public/pangshumao/data/spine/mask_case19.nii.gz'
    - '/public/pangshumao/data/spine/mask_case20.nii.gz'
  # paths to the validation datasets
  val_raw_paths:
    - '/public/pangshumao/data/spine/Case211.nii.gz'
    - '/public/pangshumao/data/spine/Case212.nii.gz'
    - '/public/pangshumao/data/spine/Case213.nii.gz'
    - '/public/pangshumao/data/spine/Case214.nii.gz'
    - '/public/pangshumao/data/spine/Case215.nii.gz'
  val_label_paths:
    - '/public/pangshumao/data/spine/mask_case211.nii.gz'
    - '/public/pangshumao/data/spine/mask_case212.nii.gz'
    - '/public/pangshumao/data/spine/mask_case213.nii.gz'
    - '/public/pangshumao/data/spine/mask_case214.nii.gz'
    - '/public/pangshumao/data/spine/mask_case215.nii.gz'
  # how many subprocesses to use for data loading
  num_workers: 8
  # data transformations/augmentations
  transformer:
    train:
      raw:
        - name: Normalize
#        - name: RandomFlip
#        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY only
          axes: [[2, 1]]
          angle_spectrum: 15
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
        - name: RandomContrast
        - name: ToTensor
          expand_dims: true
      label:
#        - name: RandomFlip
#        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY only
          axes: [[2, 1]]
          angle_spectrum: 15
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
        - name: ToTensor
          expand_dims: false
          dtype: 'long'
    test:
      raw:
        - name: Normalize
        - name: ToTensor
          expand_dims: true
      label:
        - name: ToTensor
          expand_dims: false
          dtype: 'long'
